### ISSUE TITLE
Add FallbackController and more logging for failed triggers

### ISSUE THREAD

**Issue by rbino** [edgehog-device-manager/edgehog#207]
Currently if `Astarte.process_device_event/4` returns `{:error, :cannot_process_device_event}`, the backend fails with:
```
Request: POST /tenants/test/triggers
** (exit) an exception was raised:
    ** (RuntimeError) expected action/2 to return a Plug.Conn, all plugs must receive a connection (conn) and return a connection, got: {:error, :cannot_process_device_event}
        (edgehog 0.5.0) lib/edgehog_web/controllers/trigger_controller.ex:21: EdgehogWeb.AstarteTriggerController.phoenix_controller_pipeline/2
        (phoenix 1.6.2) lib/phoenix/router.ex:355: Phoenix.Router.__call__/2
        (edgehog 0.5.0) lib/edgehog_web/endpoint.ex:21: EdgehogWeb.Endpoint.plug_builder_call/2
        (edgehog 0.5.0) lib/edgehog_web/endpoint.ex:21: EdgehogWeb.Endpoint.call/2
        (phoenix 1.6.2) lib/phoenix/endpoint/cowboy2_handler.ex:43: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.9.0) /app/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /app/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /app/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
```

A `FallbackController` should be added so that Plug can reply with a sensible HTTP error when a trigger can't be processed.

Moreover, some additional logging should be added when triggers fail to be processed to understand what went wrong.

**Comment by rbino** [comment]
Closed by #281
